######################################################################
# Automatically generated by qmake (2.01a) sö 22. okt 15:48:57 2006
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = TreeModel
TEMPLATE = app

# Input
HEADERS += objecttreemodel.h
SOURCES += main.cpp objecttreemodel.cpp
